
.PHONY: freeze image tag

freeze:
	( echo "# this file is generated by 'make freeze'"; pip freeze | grep -v '.git@' ) > requirements.freeze.txt

image:
	docker build -t zarnovican/aio-helloworld .

tag:
	docker tag zarnovican/aio-helloworld zarnovican/aio-helloworld:$(shell python setup.py --version | tr + _)
